// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)





//
// Signals declared top-level.
//

// For $a.
logic [7:0] L0_a_a0;

// For $b.
logic [7:0] L0_b_a0;

// For $rand1.
logic [3:0] L0_rand1_a0;

// For $rand2.
logic [3:0] L0_rand2_a0;

// For $reset.
logic L0_reset_a0;

// For |calc$a.
logic [7:0] CALC_a_a0;

// For |calc$aa.
logic [7:0] CALC_aa_a0,
            CALC_aa_a1;

// For |calc$b.
logic [7:0] CALC_b_a0;

// For |calc$bb.
logic [7:0] CALC_bb_a0,
            CALC_bb_a1;

// For |calc$c.
logic [7:0] CALC_c_a1,
            CALC_c_a2;

// For |calc$out.
logic [7:0] CALC_out_a2;



   // Staging of signal $rand1, which had no assignment.
   assign L0_rand1_a0[3:0] = 'x;

   // Staging of signal $rand2, which had no assignment.
   assign L0_rand2_a0[3:0] = 'x;


   //
   // Scope: |calc
   //

      // Staging of signal $a, which had no assignment.
      assign CALC_a_a0[7:0] = 'x;

      // Staging of $aa.
      always_ff @(posedge clk) CALC_aa_a1[7:0] <= CALC_aa_a0[7:0];

      // Staging of signal $b, which had no assignment.
      assign CALC_b_a0[7:0] = 'x;

      // Staging of $bb.
      always_ff @(posedge clk) CALC_bb_a1[7:0] <= CALC_bb_a0[7:0];

      // Staging of $c.
      always_ff @(posedge clk) CALC_c_a2[7:0] <= CALC_c_a1[7:0];



